// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: user_service.proto

#include "user_service.pb.h"
#include "user_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace Logic {

static const char* UserServer_method_names[] = {
  "/Logic.UserServer/Login",
};

std::unique_ptr< UserServer::Stub> UserServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< UserServer::Stub> stub(new UserServer::Stub(channel, options));
  return stub;
}

UserServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Login_(UserServer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status UserServer::Stub::Login(::grpc::ClientContext* context, const ::Logic::LoginRequest& request, ::Logic::LoginResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Logic::LoginRequest, ::Logic::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void UserServer::Stub::async::Login(::grpc::ClientContext* context, const ::Logic::LoginRequest* request, ::Logic::LoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Logic::LoginRequest, ::Logic::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void UserServer::Stub::async::Login(::grpc::ClientContext* context, const ::Logic::LoginRequest* request, ::Logic::LoginResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Logic::LoginResponse>* UserServer::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::Logic::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Logic::LoginResponse, ::Logic::LoginRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Logic::LoginResponse>* UserServer::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::Logic::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

UserServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserServer::Service, ::Logic::LoginRequest, ::Logic::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Logic::LoginRequest* req,
             ::Logic::LoginResponse* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
}

UserServer::Service::~Service() {
}

::grpc::Status UserServer::Service::Login(::grpc::ServerContext* context, const ::Logic::LoginRequest* request, ::Logic::LoginResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Logic

